name: Flask CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest flask

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Set environment variables
        env:
          FLASK_APP: app
          FLASK_ENV: development
          JWT_SECRET_KEY: 263439876012693437083642831966594211143
          TEST_BASE_URL: http://127.0.0.1:5000
        run: |
          echo "FLASK_APP=$FLASK_APP" >> $GITHUB_ENV
          echo "FLASK_ENV=$FLASK_ENV" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> $GITHUB_ENV
          echo "TEST_BASE_URL=$TEST_BASE_URL" >> $GITHUB_ENV

      - name: Start Flask server
        run: |
          flask run --host=0.0.0.0 &

      - name: Wait for Flask to start
        run: |
          while ! curl --output /dev/null --silent --head --fail ${{ env.TEST_BASE_URL }}; do
            echo "Waiting for Flask server to start..."
            sleep 5
          done

      - name: Run tests
        run: pytest
