name: Flask CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest flask

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Set environment variables
        run: |
          echo "FLASK_APP=app" >> $GITHUB_ENV
          echo "FLASK_ENV=development" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=263439876012693437083642831966594211143" >> $GITHUB_ENV
          echo "TEST_BASE_URL=http://127.0.0.1:5000" >> $GITHUB_ENV

      - name: Start Flask server
        run: |
          export FLASK_APP=app
          export FLASK_ENV=development
          flask run --host=0.0.0.0 &

      - name: Run tests
        run: pytest
