name: Flask CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest flask

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Start Flask server
        run: |
          source venv/bin/activate
          export FLASK_APP=app
          export FLASK_ENV=development
          export JWT_SECRET_KEY=263439876012693437083642831966594211143
          flask run --host=0.0.0.0 &

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
        env:
          TEST_BASE_URL: http://127.0.0.1:5000
